### PR TITLE
openSafelyCodeLists Function

### PR DESCRIPTION
**Pull request by polc1410**
OpenSafely is a project using NHS GP datasets in a secure environment.  As part of the project they have developed a set of code lists (for example all medicines classed as ACE inhibitors) that can then be matched against GP records.

They have published the code lists publicly, **and** made their publication platform available so that others can do the same!  All free of charge, all open, complete with version histories.  Their table structure is a little different to the NHS tables and so a little persuasion is required to download it with a header.  

Example use:
`
openSafelyCodeList("opensafely/ace-inhibitor-medications")
`

### CODE REVIEW

**Comment by StatsGary** [comment]
I need to check these when I have time, as they are failing the CRAN builds, so I won't be able to merge until the checks complete. Cheers

**Comment by StatsGary** [comment]
Changes accepted and will fix warnings

**Comment by StatsGary** [comment]
Merge accepted

**Comment by StatsGary** [comment]
@polc1410 I have added this function and it works great. More around documentation.

**Comment by StatsGary** [comment]
@polc1410 I will add the other functions in increments. Thanks for your contributions.

**Comment by polc1410** [comment]
You are welcome. As far as I know, the errors were in other code on the Dev branch but happy to be corrected.

This is my first ever package submission so if there are learns for me let me know.

**Comment by StatsGary** [comment]
A couple of importFrom statements in the roxygen header were needed. I am doing it in phases. Get OpenSafely in and then sort the other functions. As I do it I will tell you what else cropped up.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by StatsGary** [comment]
@polc1410 the OpenSafely function has been added. I need more time to go through the additional functions, but your name will appear on CRAN now.

**Pull request merged**
